version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../../.env
    ports:
      - "3666:3666"
    volumes:
      - "../../:/app"

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ../../.env
    ports:
      - "8080:80"

  redis:
    container_name: redis
    image: redis
    restart: always
    env_file:
      - ../../.env
    ports:
      - "6379:6379"
